name: Deploy Vue Sneakers to GitHub Pages

on:
  push:
    branches:
      - main  # Замените на вашу ветку, если она отличается

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Шаг 3: Установка зависимостей и сборка проекта
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Шаг 4: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
